using EPiServer.Shell.ObjectEditing;
using System.Collections.Generic;

namespace AlloyDemoKit.Business.SelectionFactories
{
    public class ColorSelectionFactory : ISelectionFactory
    {   
        public IEnumerable<ISelectItem> GetSelections(ExtendedMetadata metadata)
        {
            //metadata.ClientEditingClass = "alloy/editors/NonEncodingSelectionEditor";
            metadata.ClientEditingClass = "alloy/editors/NonEncodingCheckBoxListEditor";

            return new[]
            {
                new SelectItem{Value = null, Text = "Not specified"},
                new SelectItem{Value ="#CD5C5C", Text =@"Indian Red <span style=""display:inline-block;width:10px;height:10px;background-color:#CD5C5C""></span>"},
                new SelectItem{Value ="#F08080", Text =@"Light Coral <span style=""display:inline-block;width:10px;height:10px;background-color:#F08080""></span>"},
                new SelectItem{Value ="#FA8072", Text =@"Salmon <span style=""display:inline-block;width:10px;height:10px;background-color:#FA8072""></span>"},
                new SelectItem{Value ="#E9967A", Text =@"Dark Salmon <span style=""display:inline-block;width:10px;height:10px;background-color:#E9967A""></span>"},
                new SelectItem{Value ="#FFA07A", Text =@"Light Salmon <span style=""display:inline-block;width:10px;height:10px;background-color:#FFA07A""></span>"},
                new SelectItem{Value ="#DC143C", Text =@"Crimson <span style=""display:inline-block;width:10px;height:10px;background-color:#DC143C""></span>"},
                new SelectItem{Value ="#FF0000", Text =@"Red <span style=""display:inline-block;width:10px;height:10px;background-color:#FF0000""></span>"},
                new SelectItem{Value ="#B22222", Text =@"Fire Brick <span style=""display:inline-block;width:10px;height:10px;background-color:#B22222""></span>"},
                new SelectItem{Value ="#8B0000", Text =@"Dark Red <span style=""display:inline-block;width:10px;height:10px;background-color:#8B0000""></span>"},
                new SelectItem{Value ="#FFC0CB", Text =@"Pink <span style=""display:inline-block;width:10px;height:10px;background-color:#FFC0CB""></span>"},
                new SelectItem{Value ="#FFB6C1", Text =@"Light Pink <span style=""display:inline-block;width:10px;height:10px;background-color:#FFB6C1""></span>"},
                new SelectItem{Value ="#FF69B4", Text =@"Hot Pink <span style=""display:inline-block;width:10px;height:10px;background-color:#FF69B4""></span>"},
                new SelectItem{Value ="#FF1493", Text =@"Deep Pink <span style=""display:inline-block;width:10px;height:10px;background-color:#FF1493""></span>"},
                new SelectItem{Value ="#C71585", Text =@"Medium Violet Red <span style=""display:inline-block;width:10px;height:10px;background-color:#C71585""></span>"},
                new SelectItem{Value ="#DB7093", Text =@"Pale Violet Red <span style=""display:inline-block;width:10px;height:10px;background-color:#DB7093""></span>"},
                new SelectItem{Value ="#FFA07A", Text =@"Light Salmon <span style=""display:inline-block;width:10px;height:10px;background-color:#FFA07A""></span>"},
                new SelectItem{Value ="#FF7F50", Text =@"Coral <span style=""display:inline-block;width:10px;height:10px;background-color:#FF7F50""></span>"},
                new SelectItem{Value ="#FF6347", Text =@"Tomato <span style=""display:inline-block;width:10px;height:10px;background-color:#FF6347""></span>"},
                new SelectItem{Value ="#FF4500", Text =@"Orange Red <span style=""display:inline-block;width:10px;height:10px;background-color:#FF4500""></span>"},
                new SelectItem{Value ="#FF8C00", Text =@"Dark Orange <span style=""display:inline-block;width:10px;height:10px;background-color:#FF8C00""></span>"},
                new SelectItem{Value ="#FFA500", Text =@"Orange <span style=""display:inline-block;width:10px;height:10px;background-color:#FFA500""></span>"},
                new SelectItem{Value ="#FFD700", Text =@"Gold <span style=""display:inline-block;width:10px;height:10px;background-color:#FFD700""></span>"},
                new SelectItem{Value ="#FFFF00", Text =@"Yellow <span style=""display:inline-block;width:10px;height:10px;background-color:#FFFF00""></span>"},
                new SelectItem{Value ="#FFFFE0", Text =@"Light Yellow <span style=""display:inline-block;width:10px;height:10px;background-color:#FFFFE0""></span>"},
                new SelectItem{Value ="#FFFACD", Text =@"Lemon Chiffon <span style=""display:inline-block;width:10px;height:10px;background-color:#FFFACD""></span>"},
                new SelectItem{Value ="#FAFAD2", Text =@"Light Goldenrod Yellow <span style=""display:inline-block;width:10px;height:10px;background-color:#FAFAD2""></span>"},
                new SelectItem{Value ="#FFEFD5", Text =@"Papaya Whip <span style=""display:inline-block;width:10px;height:10px;background-color:#FFEFD5""></span>"},
                new SelectItem{Value ="#FFE4B5", Text =@"Moccasin <span style=""display:inline-block;width:10px;height:10px;background-color:#FFE4B5""></span>"},
                new SelectItem{Value ="#FFDAB9", Text =@"Peach Puff <span style=""display:inline-block;width:10px;height:10px;background-color:#FFDAB9""></span>"},
                new SelectItem{Value ="#EEE8AA", Text =@"Pale Goldenrod <span style=""display:inline-block;width:10px;height:10px;background-color:#EEE8AA""></span>"},
                new SelectItem{Value ="#F0E68C", Text =@"Khaki <span style=""display:inline-block;width:10px;height:10px;background-color:#F0E68C""></span>"},
                new SelectItem{Value ="#BDB76B", Text =@"Dark Khaki <span style=""display:inline-block;width:10px;height:10px;background-color:#BDB76B""></span>"},
                new SelectItem{Value ="#E6E6FA", Text =@"Lavender <span style=""display:inline-block;width:10px;height:10px;background-color:#E6E6FA""></span>"},
                new SelectItem{Value ="#D8BFD8", Text =@"Thistle <span style=""display:inline-block;width:10px;height:10px;background-color:#D8BFD8""></span>"},
                new SelectItem{Value ="#DDA0DD", Text =@"Plum <span style=""display:inline-block;width:10px;height:10px;background-color:#DDA0DD""></span>"},
                new SelectItem{Value ="#EE82EE", Text =@"Violet <span style=""display:inline-block;width:10px;height:10px;background-color:#EE82EE""></span>"},
                new SelectItem{Value ="#DA70D6", Text =@"Orchid <span style=""display:inline-block;width:10px;height:10px;background-color:#DA70D6""></span>"},
                new SelectItem{Value ="#FF00FF", Text =@"Fuchsia <span style=""display:inline-block;width:10px;height:10px;background-color:#FF00FF""></span>"},
                new SelectItem{Value ="#FF00FF", Text =@"Magenta <span style=""display:inline-block;width:10px;height:10px;background-color:#FF00FF""></span>"},
                new SelectItem{Value ="#BA55D3", Text =@"Medium Orchid <span style=""display:inline-block;width:10px;height:10px;background-color:#BA55D3""></span>"},
                new SelectItem{Value ="#9370DB", Text =@"Medium Purple <span style=""display:inline-block;width:10px;height:10px;background-color:#9370DB""></span>"},
                new SelectItem{Value ="#663399", Text =@"Rebecca Purple <span style=""display:inline-block;width:10px;height:10px;background-color:#663399""></span>"},
                new SelectItem{Value ="#8A2BE2", Text =@"Blue Violet <span style=""display:inline-block;width:10px;height:10px;background-color:#8A2BE2""></span>"},
                new SelectItem{Value ="#9400D3", Text =@"Dark Violet <span style=""display:inline-block;width:10px;height:10px;background-color:#9400D3""></span>"},
                new SelectItem{Value ="#9932CC", Text =@"Dark Orchid <span style=""display:inline-block;width:10px;height:10px;background-color:#9932CC""></span>"},
                new SelectItem{Value ="#8B008B", Text =@"Dark Magenta <span style=""display:inline-block;width:10px;height:10px;background-color:#8B008B""></span>"},
                new SelectItem{Value ="#800080", Text =@"Purple <span style=""display:inline-block;width:10px;height:10px;background-color:#800080""></span>"},
                new SelectItem{Value ="#4B0082", Text =@"Indigo <span style=""display:inline-block;width:10px;height:10px;background-color:#4B0082""></span>"},
                new SelectItem{Value ="#6A5ACD", Text =@"Slate Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#6A5ACD""></span>"},
                new SelectItem{Value ="#483D8B", Text =@"Dark Slate Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#483D8B""></span>"},
                new SelectItem{Value ="#7B68EE", Text =@"Medium Slate Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#7B68EE""></span>"},
                new SelectItem{Value ="#ADFF2F", Text =@"Green Yellow <span style=""display:inline-block;width:10px;height:10px;background-color:#ADFF2F""></span>"},
                new SelectItem{Value ="#7FFF00", Text =@"Chartreuse <span style=""display:inline-block;width:10px;height:10px;background-color:#7FFF00""></span>"},
                new SelectItem{Value ="#7CFC00", Text =@"Lawn Green <span style=""display:inline-block;width:10px;height:10px;background-color:#7CFC00""></span>"},
                new SelectItem{Value ="#00FF00", Text =@"Lime <span style=""display:inline-block;width:10px;height:10px;background-color:#00FF00""></span>"},
                new SelectItem{Value ="#32CD32", Text =@"Lime Green <span style=""display:inline-block;width:10px;height:10px;background-color:#32CD32""></span>"},
                new SelectItem{Value ="#98FB98", Text =@"Pale Green <span style=""display:inline-block;width:10px;height:10px;background-color:#98FB98""></span>"},
                new SelectItem{Value ="#90EE90", Text =@"Light Green <span style=""display:inline-block;width:10px;height:10px;background-color:#90EE90""></span>"},
                new SelectItem{Value ="#00FA9A", Text =@"Medium Spring Green <span style=""display:inline-block;width:10px;height:10px;background-color:#00FA9A""></span>"},
                new SelectItem{Value ="#00FF7F", Text =@"Spring Green <span style=""display:inline-block;width:10px;height:10px;background-color:#00FF7F""></span>"},
                new SelectItem{Value ="#3CB371", Text =@"Medium Sea Green <span style=""display:inline-block;width:10px;height:10px;background-color:#3CB371""></span>"},
                new SelectItem{Value ="#2E8B57", Text =@"Sea Green <span style=""display:inline-block;width:10px;height:10px;background-color:#2E8B57""></span>"},
                new SelectItem{Value ="#228B22", Text =@"Forest Green <span style=""display:inline-block;width:10px;height:10px;background-color:#228B22""></span>"},
                new SelectItem{Value ="#008000", Text =@"Green <span style=""display:inline-block;width:10px;height:10px;background-color:#008000""></span>"},
                new SelectItem{Value ="#006400", Text =@"Dark Green <span style=""display:inline-block;width:10px;height:10px;background-color:#006400""></span>"},
                new SelectItem{Value ="#9ACD32", Text =@"Yellow Green <span style=""display:inline-block;width:10px;height:10px;background-color:#9ACD32""></span>"},
                new SelectItem{Value ="#6B8E23", Text =@"Olive Drab <span style=""display:inline-block;width:10px;height:10px;background-color:#6B8E23""></span>"},
                new SelectItem{Value ="#808000", Text =@"Olive <span style=""display:inline-block;width:10px;height:10px;background-color:#808000""></span>"},
                new SelectItem{Value ="#556B2F", Text =@"Dark Olive Green <span style=""display:inline-block;width:10px;height:10px;background-color:#556B2F""></span>"},
                new SelectItem{Value ="#66CDAA", Text =@"Medium Aquamarine <span style=""display:inline-block;width:10px;height:10px;background-color:#66CDAA""></span>"},
                new SelectItem{Value ="#8FBC8B", Text =@"Dark Sea Green <span style=""display:inline-block;width:10px;height:10px;background-color:#8FBC8B""></span>"},
                new SelectItem{Value ="#20B2AA", Text =@"Light Sea Green <span style=""display:inline-block;width:10px;height:10px;background-color:#20B2AA""></span>"},
                new SelectItem{Value ="#008B8B", Text =@"Dark Cyan <span style=""display:inline-block;width:10px;height:10px;background-color:#008B8B""></span>"},
                new SelectItem{Value ="#008080", Text =@"Teal <span style=""display:inline-block;width:10px;height:10px;background-color:#008080""></span>"},
                new SelectItem{Value ="#00FFFF", Text =@"Aqua <span style=""display:inline-block;width:10px;height:10px;background-color:#00FFFF""></span>"},
                new SelectItem{Value ="#00FFFF", Text =@"Cyan <span style=""display:inline-block;width:10px;height:10px;background-color:#00FFFF""></span>"},
                new SelectItem{Value ="#E0FFFF", Text =@"Light Cyan <span style=""display:inline-block;width:10px;height:10px;background-color:#E0FFFF""></span>"},
                new SelectItem{Value ="#AFEEEE", Text =@"Pale Turquoise <span style=""display:inline-block;width:10px;height:10px;background-color:#AFEEEE""></span>"},
                new SelectItem{Value ="#7FFFD4", Text =@"Aquamarine <span style=""display:inline-block;width:10px;height:10px;background-color:#7FFFD4""></span>"},
                new SelectItem{Value ="#40E0D0", Text =@"Turquoise <span style=""display:inline-block;width:10px;height:10px;background-color:#40E0D0""></span>"},
                new SelectItem{Value ="#48D1CC", Text =@"Medium Turquoise <span style=""display:inline-block;width:10px;height:10px;background-color:#48D1CC""></span>"},
                new SelectItem{Value ="#00CED1", Text =@"Dark Turquoise <span style=""display:inline-block;width:10px;height:10px;background-color:#00CED1""></span>"},
                new SelectItem{Value ="#5F9EA0", Text =@"Cadet Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#5F9EA0""></span>"},
                new SelectItem{Value ="#4682B4", Text =@"Steel Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#4682B4""></span>"},
                new SelectItem{Value ="#B0C4DE", Text =@"Light Steel Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#B0C4DE""></span>"},
                new SelectItem{Value ="#B0E0E6", Text =@"Powder Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#B0E0E6""></span>"},
                new SelectItem{Value ="#ADD8E6", Text =@"Light Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#ADD8E6""></span>"},
                new SelectItem{Value ="#87CEEB", Text =@"Sky Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#87CEEB""></span>"},
                new SelectItem{Value ="#87CEFA", Text =@"Light Sky Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#87CEFA""></span>"},
                new SelectItem{Value ="#00BFFF", Text =@"Deep Sky Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#00BFFF""></span>"},
                new SelectItem{Value ="#1E90FF", Text =@"Dodger Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#1E90FF""></span>"},
                new SelectItem{Value ="#6495ED", Text =@"Cornflower Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#6495ED""></span>"},
                new SelectItem{Value ="#7B68EE", Text =@"Medium Slate Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#7B68EE""></span>"},
                new SelectItem{Value ="#4169E1", Text =@"Royal Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#4169E1""></span>"},
                new SelectItem{Value ="#0000FF", Text =@"Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#0000FF""></span>"},
                new SelectItem{Value ="#0000CD", Text =@"Medium Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#0000CD""></span>"},
                new SelectItem{Value ="#00008B", Text =@"Dark Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#00008B""></span>"},
                new SelectItem{Value ="#000080", Text =@"Navy <span style=""display:inline-block;width:10px;height:10px;background-color:#000080""></span>"},
                new SelectItem{Value ="#191970", Text =@"Midnight Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#191970""></span>"},
                new SelectItem{Value ="#FFF8DC", Text =@"Cornsilk <span style=""display:inline-block;width:10px;height:10px;background-color:#FFF8DC""></span>"},
                new SelectItem{Value ="#FFEBCD", Text =@"Blanched Almond <span style=""display:inline-block;width:10px;height:10px;background-color:#FFEBCD""></span>"},
                new SelectItem{Value ="#FFE4C4", Text =@"Bisque <span style=""display:inline-block;width:10px;height:10px;background-color:#FFE4C4""></span>"},
                new SelectItem{Value ="#FFDEAD", Text =@"Navajo White <span style=""display:inline-block;width:10px;height:10px;background-color:#FFDEAD""></span>"},
                new SelectItem{Value ="#F5DEB3", Text =@"Wheat <span style=""display:inline-block;width:10px;height:10px;background-color:#F5DEB3""></span>"},
                new SelectItem{Value ="#DEB887", Text =@"Burly Wood <span style=""display:inline-block;width:10px;height:10px;background-color:#DEB887""></span>"},
                new SelectItem{Value ="#D2B48C", Text =@"Tan <span style=""display:inline-block;width:10px;height:10px;background-color:#D2B48C""></span>"},
                new SelectItem{Value ="#BC8F8F", Text =@"Rosy Brown <span style=""display:inline-block;width:10px;height:10px;background-color:#BC8F8F""></span>"},
                new SelectItem{Value ="#F4A460", Text =@"Sandy Brown <span style=""display:inline-block;width:10px;height:10px;background-color:#F4A460""></span>"},
                new SelectItem{Value ="#DAA520", Text =@"Goldenrod <span style=""display:inline-block;width:10px;height:10px;background-color:#DAA520""></span>"},
                new SelectItem{Value ="#B8860B", Text =@"Dark Goldenrod <span style=""display:inline-block;width:10px;height:10px;background-color:#B8860B""></span>"},
                new SelectItem{Value ="#CD853F", Text =@"Peru <span style=""display:inline-block;width:10px;height:10px;background-color:#CD853F""></span>"},
                new SelectItem{Value ="#D2691E", Text =@"Chocolate <span style=""display:inline-block;width:10px;height:10px;background-color:#D2691E""></span>"},
                new SelectItem{Value ="#8B4513", Text =@"Saddle Brown <span style=""display:inline-block;width:10px;height:10px;background-color:#8B4513""></span>"},
                new SelectItem{Value ="#A0522D", Text =@"Sienna <span style=""display:inline-block;width:10px;height:10px;background-color:#A0522D""></span>"},
                new SelectItem{Value ="#A52A2A", Text =@"Brown <span style=""display:inline-block;width:10px;height:10px;background-color:#A52A2A""></span>"},
                new SelectItem{Value ="#800000", Text =@"Maroon <span style=""display:inline-block;width:10px;height:10px;background-color:#800000""></span>"},
                new SelectItem{Value ="#FFFFFF", Text =@"White <span style=""display:inline-block;width:10px;height:10px;background-color:#FFFFFF""></span>"},
                new SelectItem{Value ="#FFFAFA", Text =@"Snow <span style=""display:inline-block;width:10px;height:10px;background-color:#FFFAFA""></span>"},
                new SelectItem{Value ="#F0FFF0", Text =@"Honey Dew <span style=""display:inline-block;width:10px;height:10px;background-color:#F0FFF0""></span>"},
                new SelectItem{Value ="#F5FFFA", Text =@"Mint Cream <span style=""display:inline-block;width:10px;height:10px;background-color:#F5FFFA""></span>"},
                new SelectItem{Value ="#F0FFFF", Text =@"Azure <span style=""display:inline-block;width:10px;height:10px;background-color:#F0FFFF""></span>"},
                new SelectItem{Value ="#F0F8FF", Text =@"Alice Blue <span style=""display:inline-block;width:10px;height:10px;background-color:#F0F8FF""></span>"},
                new SelectItem{Value ="#F8F8FF", Text =@"Ghost White <span style=""display:inline-block;width:10px;height:10px;background-color:#F8F8FF""></span>"},
                new SelectItem{Value ="#F5F5F5", Text =@"White Smoke <span style=""display:inline-block;width:10px;height:10px;background-color:#F5F5F5""></span>"},
                new SelectItem{Value ="#FFF5EE", Text =@"Sea Shell <span style=""display:inline-block;width:10px;height:10px;background-color:#FFF5EE""></span>"},
                new SelectItem{Value ="#F5F5DC", Text =@"Beige <span style=""display:inline-block;width:10px;height:10px;background-color:#F5F5DC""></span>"},
                new SelectItem{Value ="#FDF5E6", Text =@"Old Lace <span style=""display:inline-block;width:10px;height:10px;background-color:#FDF5E6""></span>"},
                new SelectItem{Value ="#FFFAF0", Text =@"Floral White <span style=""display:inline-block;width:10px;height:10px;background-color:#FFFAF0""></span>"},
                new SelectItem{Value ="#FFFFF0", Text =@"Ivory <span style=""display:inline-block;width:10px;height:10px;background-color:#FFFFF0""></span>"},
                new SelectItem{Value ="#FAEBD7", Text =@"Antique White <span style=""display:inline-block;width:10px;height:10px;background-color:#FAEBD7""></span>"},
                new SelectItem{Value ="#FAF0E6", Text =@"Linen <span style=""display:inline-block;width:10px;height:10px;background-color:#FAF0E6""></span>"},
                new SelectItem{Value ="#FFF0F5", Text =@"Lavender Blush <span style=""display:inline-block;width:10px;height:10px;background-color:#FFF0F5""></span>"},
                new SelectItem{Value ="#FFE4E1", Text =@"Misty Rose <span style=""display:inline-block;width:10px;height:10px;background-color:#FFE4E1""></span>"},
                new SelectItem{Value ="#DCDCDC", Text =@"Gainsboro <span style=""display:inline-block;width:10px;height:10px;background-color:#DCDCDC""></span>"},
                new SelectItem{Value ="#D3D3D3", Text =@"Light Gray <span style=""display:inline-block;width:10px;height:10px;background-color:#D3D3D3""></span>"},
                new SelectItem{Value ="#C0C0C0", Text =@"Silver <span style=""display:inline-block;width:10px;height:10px;background-color:#C0C0C0""></span>"},
                new SelectItem{Value ="#A9A9A9", Text =@"Dark Gray <span style=""display:inline-block;width:10px;height:10px;background-color:#A9A9A9""></span>"},
                new SelectItem{Value ="#808080", Text =@"Gray <span style=""display:inline-block;width:10px;height:10px;background-color:#808080""></span>"},
                new SelectItem{Value ="#696969", Text =@"Dim Gray <span style=""display:inline-block;width:10px;height:10px;background-color:#696969""></span>"},
                new SelectItem{Value ="#778899", Text =@"Light Slate Gray <span style=""display:inline-block;width:10px;height:10px;background-color:#778899""></span>"},
                new SelectItem{Value ="#708090", Text =@"Slate Gray <span style=""display:inline-block;width:10px;height:10px;background-color:#708090""></span>"},
                new SelectItem{Value ="#2F4F4F", Text =@"Dark Slate Gray <span style=""display:inline-block;width:10px;height:10px;background-color:#2F4F4F""></span>"},
                new SelectItem{Value ="#000000", Text =@"Black <span style=""display:inline-block;width:10px;height:10px;background-color:#000000""></span>"},
            };
        }
    }
}